version: '3.4'

services:
  blazor-sandbox:
    image: ${DOCKER_REGISTRY-}blazorsandbox
    build:
      context: .
      dockerfile: blazor-sandbox/Dockerfile

  data-sandbox:
    image: ${DOCKER_REGISTRY-}datasandbox
    build:
      context: .
      dockerfile: data-sandbox/Dockerfile


  grpc-sandbox:
    image: ${DOCKER_REGISTRY-}grpcsandbox
    build:
      context: .
      dockerfile: grpc-sandbox/Dockerfile

